AucfoDemo/AucfoDemo.WebUI/Models/BooksCategory/BooksCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AucfoDemo.WebUI.Models.BooksCategory
{
    public class BooksCategoryViewModel
    {
        public Guid Id { get; set; }

        [Required]
        [StringLength(255),Column(TypeName = "varchar")]
        public string BooksCategory_Title { get; set; }
    }
}

AucfoDemo/AucfoDemo.WebUI/Controllers/BooksCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AucfoDemo.WebUI.Models.BooksCategory;
using AutofacDemo.IBLL;
namespace AucfoDemo.WebUI.Controllers
{
    public class BooksCategoryController : Controller
    {
        private readonly IBooksCategoryManager booksCategory;

        public BooksCategoryController(IBooksCategoryManager booksCategory)
        {
            this.booksCategory = booksCategory;
        }
        // GET: BooksCategory
        public async Task<ActionResult> Index()
        {
            var list = await  booksCategory.GetData();
            return View(list);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(BooksCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                booksCategory.CreateBooksCategoryAsync(model.BooksCategory_Title);
                return RedirectToAction("Index");
            }

            return View();

        }



    }
}

AucfoDemo/AucfoDemo.WebUI/Views/BooksCategory/Add.cshtml
@model AucfoDemo.WebUI.Models.BooksCategory.BooksCategoryViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm("Add","BooksCategory",FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>BooksCategoryViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.BooksCategory_Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BooksCategory_Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BooksCategory_Title, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

AucfoDemo/AucfoDemo.WebUI/Views/BooksCategory/Index.cshtml
@model IEnumerable<AutofacDemo.Dto.BooksCategoryDto>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Add")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BooksCategory_Title)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BooksCategory_Title)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>